/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/films` | `/films`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pass` | `/pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/surveys` | `/surveys`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/films` | `/films`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pass` | `/pass`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/surveys` | `/surveys`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/daily${`?${string}` | `#${string}` | ''}` | `/daily${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/films${`?${string}` | `#${string}` | ''}` | `/films${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/info${`?${string}` | `#${string}` | ''}` | `/info${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pass${`?${string}` | `#${string}` | ''}` | `/pass${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/program${`?${string}` | `#${string}` | ''}` | `/program${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/surveys${`?${string}` | `#${string}` | ''}` | `/surveys${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/films` | `/films`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/info` | `/info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pass` | `/pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/surveys` | `/surveys`; params?: Router.UnknownInputParams; };
    }
  }
}
